import { defineArrayMember, defineField, defineType } from "sanity";
import { BookIcon } from "@sanity/icons/Book";
import { ACCENT_OPTIONS, ICON_OPTIONS } from "./options.js";

export const trainingModule = defineType({
  name: "trainingModule",
  title: "Training module",
  type: "document",
  icon: BookIcon,
  groups: [
    { name: "details", title: "Details", default: true },
    { name: "sections", title: "Sections" },
    { name: "look", title: "Look and feel" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Module title",
      type: "string",
      group: "details",
      description: "For example: Candidate Management.",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "slug",
      title: "Web address",
      type: "slug",
      group: "details",
      description: "The end of the page address, for example 'candidate'. Click Generate to create it from the title. Avoid changing it once the module is live, as links to it will stop working.",
      options: { source: "title", maxLength: 40 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "eyebrow",
      title: "Label above the title",
      type: "string",
      group: "details",
      description: "One or two words shown in small capitals, for example 'People' or 'Growth'.",
      validation: (r) => r.max(24),
    }),
    defineField({
      name: "subtitle",
      title: "Short description",
      type: "string",
      group: "details",
      description: "One line shown on the module card and under the title, for example 'Source, screen, brief and manage expectations'.",
      validation: (r) => r.required().max(90),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "category" }],
      group: "details",
      description: "Optional. Used to group modules on the home page.",
    }),
    defineField({
      name: "order",
      title: "Display order",
      type: "number",
      group: "details",
      description: "Lower numbers appear first on the home page. Use 10, 20, 30 and so on, so you can slot new modules in between.",
      validation: (r) => r.required().integer().min(0),
    }),
    defineField({
      name: "estimatedMinutes",
      title: "Time to complete, in minutes (optional)",
      type: "number",
      group: "details",
      description: "Leave empty and the hub works it out from the amount of content.",
      validation: (r) => r.integer().min(1).max(240),
    }),
    defineField({
      name: "sections",
      title: "Sections",
      type: "array",
      group: "sections",
      description: "The sections learners work through, in order. Drag to reorder.",
      of: [defineArrayMember({ type: "section" })],
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "icon",
      title: "Icon",
      type: "string",
      group: "look",
      description: "Shown on the module card.",
      options: { list: ICON_OPTIONS },
      initialValue: "book-open",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "accent",
      title: "Colour",
      type: "string",
      group: "look",
      description: "The gradient used for this module's card and page header.",
      options: { list: ACCENT_OPTIONS, layout: "radio" },
      initialValue: "brand",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Header photo (optional)",
      type: "image",
      group: "look",
      description: "A person photo for the top of the module page. A cut-out with a transparent background (PNG or WebP) looks best.",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Image description", type: "string", description: "Describe the photo for people using screen readers. Leave empty if it's purely decorative." }],
    }),
  ],
  orderings: [{ title: "Display order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "subtitle", order: "order", media: "heroImage", sections: "sections" },
    prepare: ({ title, subtitle, order, media, sections = [] }) => ({
      title: `${order ?? "–"}. ${title || "Untitled module"}`,
      subtitle: `${sections.length} sections · ${subtitle || ""}`,
      media,
    }),
  },
});
